#!/usr/bin/env bash

print_usage(){
	cat << EOF
Usage: $(basename ${BASH_SOURCE}) [OPTION]... [GIT_PROJECT_FOLDER...]
Show statuses of Git projects given in arguments or all projects found in the current directory when no argument specified.

Options:
  -f	Perform git fetch.

EOF
}

BLACK=$(tput setaf 0)
RED=$(tput setaf 1)
ORANGE=$(tput setaf 172)
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
LIME_YELLOW=$(tput setaf 190)
POWDER_BLUE=$(tput setaf 153)
BLUE=$(tput setaf 4)
MAGENTA=$(tput setaf 5)
CYAN=$(tput setaf 6)
WHITE=$(tput setaf 7)
BRIGHT=$(tput bold)
NORMAL=$(tput sgr0)
BLINK=$(tput blink)
REVERSE=$(tput smso)
UNDERLINE=$(tput smul)
BOLD=$(tput bold)

CURRENT_WORKING_DIRECTORY="$(pwd)"
trap "cd '${CURRENT_WORKING_DIRECTORY}'" 0

RUN_FETCH_ON_GIT_REPO="false"
DEBUG="false"
while getopts "hfd" ARG; do
	case "${ARG}" in
		h)
			print_usage
			exit 0
			;;
		f)
			RUN_FETCH_ON_GIT_REPO="true"
			;;
		d)
			DEBUG="true"
			;;
		*)
			printf "Unknown option: %s\n" "${OPTARG}" 1>&2
			print_usage
			exit 1
			;;
	esac
done
shift $((OPTIND-1))

# Collect folders to inspect
FOLDER_TO_INSPECT_ARRAY=()
if [[ "${#}" -eq 0 ]]; then
	# Check if CWD is already a GIT project then we add the parent folder only
	if [[ -d ".git" ]]; then
		FOLDER_TO_INSPECT_ARRAY+=( "." )
	else
		for FOLDER in *; do
			if [[ ! -d "${FOLDER}" ]]; then
				continue
			fi
			FOLDER_TO_INSPECT_ARRAY+=( "${FOLDER}" )
		done
	fi
else
	for FOLDER in "${@}"; do
		FOLDER_TO_INSPECT_ARRAY+=( "${FOLDER}" )
	done
fi

# Filter GIT repositories
GIT_REPO_DIR_ARRAY=()
for FOLDER_TO_INSPECT in "${FOLDER_TO_INSPECT_ARRAY[@]}"; do
	FOLDER_TO_INSPECT_RESOLVED_PATH=$(readlink -e "${FOLDER_TO_INSPECT}")
	if [[ "${?}" != 0 ]]; then
		printf "Cannot find Git project [%s]\n" "${FOLDER_TO_INSPECT_RESOLVED_PATH}"
		continue
	fi
	if [[ ! -d "${FOLDER_TO_INSPECT_RESOLVED_PATH}" ]]; then
		printf "[%s] is not a folder%s\n"
		continue
	fi
	if [[ ! -d "${FOLDER_TO_INSPECT_RESOLVED_PATH}/.git" ]]; then
		printf "[%s] is not a Git repository\n" "${FOLDER_TO_INSPECT_RESOLVED_PATH}"
		continue
	fi
	GIT_REPO_DIR_ARRAY+=( "${FOLDER_TO_INSPECT_RESOLVED_PATH}" )
done

GIT_BRANCH_LINE_REGEX="^( |\*)[[:space:]]+(.+)[[:space:]]+(.+)[[:space:]]+\[(.+)\][[:space:]]+(.+)$"

for GIT_REPO_DIR in "${GIT_REPO_DIR_ARRAY[@]}"; do
	cd "${GIT_REPO_DIR}"
	
	GIT_REPO_NAME=$(basename "${GIT_REPO_DIR}")
	
	# Retrieve current branch
	# `--show-current` parameter of `git branch` has been added in Git v2.22 so we use `git rev-parse` instead.
	#CURRENT_LOCAL_BRANCH=$(git branch --show-current 2>/dev/null)
	CURRENT_LOCAL_BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null)
	if [[ "${?}" -ne 0 ]]; then
		printf " Cannot retrieve local current branch\n"
		continue
	fi
	
	# Retrieve local changes count
	PENDING_CHANGE_COUNT=$(git status --porcelain | wc -l 2>&1)
	if [[ "${?}" -ne 0 ]]; then
		printf "  Something went wrong while checking for local changes\n"
		continue
	fi
	
	GIT_REPO_PENDING_CHANGES=""
	if [[ "${PENDING_CHANGE_COUNT}" -ne 0 ]]; then
		GIT_REPO_PENDING_CHANGES=" !! ${PENDING_CHANGE_COUNT} pending change(s)"
	fi
	printf "${GREEN}\\u23FA %s${NORMAL}%s\n" "${GIT_REPO_NAME}" "${GIT_REPO_PENDING_CHANGES}"
	
	# GIT fetch
	if ${RUN_FETCH_ON_GIT_REPO}; then
		git fetch >/dev/null 2>/dev/null
		if [[ "${?}" -ne 0 ]]; then
			printf " Something went wrong during git fetch\n"
			continue
		fi
	fi
	
	GIT_BRANCH=$(git branch -vv)
	while IFS= read -r GIT_BRANCH_LINE; do
		if [[ ! "${GIT_BRANCH_LINE}" =~ ${GIT_BRANCH_LINE_REGEX} ]]; then
			printf "!ERROR! GIT_BRANCH_LINE is not well formed [%s]\n" "${GIT_BRANCH_LINE}"
			break
		fi
		
		if ${DEBUG}; then
			printf "GIT_BRANCH_LINE[%s]\n" "${GIT_BRANCH_LINE}"
		fi
		
		GIT_BRANCH_LINE_IS_CURRENT_BRANCH="${BASH_REMATCH[1]}"
		GIT_BRANCH_LINE_BRANCH_NAME="${BASH_REMATCH[2]}"
		GIT_BRANCH_LINE_UPSTREAM="${BASH_REMATCH[4]}"
		
		if [[ "${CURRENT_LOCAL_BRANCH}" == '*' ]]; then
			printf "   %s %s \\u279C ${BLUE}%s${NORMAL}\n" "${GIT_BRANCH_LINE_IS_CURRENT_BRANCH}" "${GIT_BRANCH_LINE_BRANCH_NAME}" "${GIT_BRANCH_LINE_UPSTREAM}"
		else
			printf "   %s ${YELLOW}%s${NORMAL} \\u279C ${BLUE}%s${NORMAL}\n" "${GIT_BRANCH_LINE_IS_CURRENT_BRANCH}" "${GIT_BRANCH_LINE_BRANCH_NAME}" "${GIT_BRANCH_LINE_UPSTREAM}"
		fi
	done <<< "${GIT_BRANCH}"
	
	printf "\n"
done
